spring:
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments : true
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/koroot?serverTimezone=UTC&characterEncoding=UTF-8
#    username: admin2017
#    password: admin2017

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://umj7-021.cafe24.com:3306/koroot2452?serverTimezone=UTC&characterEncoding=UTF-8
    username: koroot2452
    password: koroot2451

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/koroot2452?serverTimezone=UTC&characterEncoding=UTF-8
#    username: koroot2452
#    password: koroot2451

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/koroot2452?serverTimezone=UTC&characterEncoding=UTF-8
    username: koroot2452
    password: koroot2451